### ISSUE TITLE
Predictor Class error

### ISSUE THREAD

**Issue by Anafeyka** [idealo/image-super-resolution#103]
win 10
python 3.6.8
ISR install pip

Work

```
import numpy as np
from os.path import expanduser
from PIL import Image
from ISR.models import RDN, RRDN

model = RRDN(weights='gans')

img = Image.open(expanduser('data/input/test_images/test.png'))
lr_img = np.array(img)

sr_img = model.predict(lr_img)
output = Image.fromarray(sr_img)
output.save(expanduser('data/out.png'))
```

Code error
```
from ISR.predict import Predictor
predictor = Predictor(input_dir='data/input/test_images/', output_dir='data/output')
predictor.get_predictions(model=RRDN, weights_path='weights/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5')
```

Error
```
C:\pytest\ISR>python test.py
Traceback (most recent call last):
  File "test.py", line 66, in <module>
    predictor.get_predictions(model=RRDN, weights_path='weights/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5')
NameError: name 'RRDN' is not defined
```

**Comment by jahyuky** [comment]
You defined your RRDN model as 'model' in line 6 in 'Work' block.
So, in line 3 in 'Code error' block, you have to give a defined model as the 'model' parameter.

Below code may solve this problem
`predictor.get_predictions(model=model, weights_path='weights/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5')`

**Comment by Anafeyka** [comment]
```
2020-02-05 04:36:44.472470: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Loaded weights from
 > weights\rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5
Traceback (most recent call last):
  File "testPred.py", line 42, in <module>
    predictor.get_predictions(model=rdn, weights_path='weights/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')
  File "C:\Python36-64\lib\site-packages\ISR\predict\predictor.py", line 85, in get_predictions
    weights_conf = self._load_weights()
  File "C:\Python36-64\lib\site-packages\ISR\predict\predictor.py", line 58, in _load_weights
    self.model.model.load_weights(self.weights_path)
  File "C:\Python36-64\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 181, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "C:\Python36-64\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1139, in load_weights
    if _is_hdf5_filepath(filepath):
  File "C:\Python36-64\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 1449, in _is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'WindowsPath' object has no attribute 'endswith'
```
If I replace in Predictor.py string 58 on
self.model.model.load_weights(str(self.weights_path))

```
Loaded weights from
 > weights\rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5
Traceback (most recent call last):
  File "testpred.py", line 42, in <module>
    predictor.get_predictions(model=rdn, weights_path='weights/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')
  File "C:\Python36-64\lib\site-packages\ISR\predict\predictor.py", line 85, in get_predictions
    weights_conf = self._load_weights()
  File "C:\Python36-64\lib\site-packages\ISR\predict\predictor.py", line 65, in _load_weights
    conf = yaml.load(session_config_path.read_text(), Loader=yaml.FullLoader)
  File "C:\Python36-64\lib\site-packages\yaml\__init__.py", line 114, in load
    return loader.get_single_data()
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 43, in get_single_data
    return self.construct_document(node)
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 52, in construct_document
    for dummy in generator:
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 210, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 135, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 94, in construct_object
    data = constructor(self, tag_suffix, node)
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 551, in construct_python_name
    return self.find_python_name(suffix, node.start_mark)
  File "C:\Python36-64\lib\site-packages\yaml\constructor.py", line 538, in find_python_name
    "module %r is not imported" % module_name, mark)
yaml.constructor.ConstructorError: while constructing a Python object
module 'ISR.utils.metrics' is not imported
  in "<unicode string>", line 47, column 18:
          generator: &id001 !!python/name:ISR.utils.m ...

```

**Comment by jahyuky** [comment]
Your proposed solution is exactly same as mine. In my case, it works well. Please check whether your import 'ISR.utils.metrics' during your runtime.

**Comment by Anafeyka** [comment]
Yes, I really forgot to import ISR.utils.metrics
Now everything works thanks.

**Comment by cfrancesco** [comment]
@jahyuky thanks!
