### ISSUE TITLE
save model error

### ISSUE THREAD

**Issue by sangjun04** [idealo/image-super-resolution#107]
I am trying to save the entire network architect + weights via model.save function instead of using model.save_weights which only saves weight value.
However, TypeError: can't pickle _thread.RLock objects pops up.

The error message is the following..

val_generator_PSNR_Y improved from       -inf to    7.83801
Saving weights
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    monitored_metrics={'val_generator_PSNR_Y': 'max'}
  File "C:\Users\Administrator\Desktop\PROJECTS\SuperResolution\ISR\train\trainer.py", line 384, in train
    metrics=monitored_metrics,
  File "C:\Users\Administrator\Desktop\PROJECTS\SuperResolution\ISR\utils\train_helper.py", line 258, in on_epoch_end
    self._save_weights(epoch, generator, discriminator, metric=metric, best=True)
  File "C:\Users\Administrator\Desktop\PROJECTS\SuperResolution\ISR\utils\train_helper.py", line 189, in _save_weights
    generator.save('test_weight/test_model.hdf5')
  File "C:\ProgramData\Anaconda3\envs\super\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 975, in save
    signatures, options)
  File "C:\ProgramData\Anaconda3\envs\super\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 112, in save_model
    model, filepath, overwrite, include_optimizer)
  File "C:\ProgramData\Anaconda3\envs\super\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 99, in save_model_to_hd
    model_metadata = saving_utils.model_metadata(model, include_optimizer)
  File "C:\ProgramData\Anaconda3\envs\super\lib\site-packages\tensorflow_core\python\keras\saving\saving_utils.py", line 162, in model_metadata
    model_config['config'] = model.get_config()
  File "C:\ProgramData\Anaconda3\envs\super\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 887, in get_config
    return copy.deepcopy(get_network_config(self))
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\ProgramData\Anaconda3\envs\super\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects

Any tips or idea on how to resolve this issue?

Thanks,

**Comment by cfrancesco** [comment]
This is a Tensorflow issue, due to a custom layer. Check out https://www.tensorflow.org/tutorials/keras/save_and_load for more info, specifically the SavedModel type and the "saving custom objects" part.

Saluti

**Comment by cfrancesco** [comment]
Also, you should be able to avoid this issue entirely by using the RDN model, which can use (and is defaulted to) a standard upscaling layer rather than the pixel shuffle operation, although the latter should be preferred.
You can change the upscaling layer adding the `upscaling` parameter at model declaration, as such:
`RDN(arch_params={'C': 3, 'D': 10, 'G': 64, 'G0': 64, 'x': 2}, upscaling='ups')`

To use the shuffle operation use `'shuffle'` instead.
