### ISSUE TITLE
can't run Dockerfile.cpu. AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by usk81** [idealo/image-super-resolution#163]
1st
```sh
docker run -v $(pwd)/data/:/home/isr/data -v $(pwd)/weights/:/home/isr/weights -v $(pwd)/config.yml:/home/isr/config.yml -it isr -p -d -c config.yml
```

2nd (change weights directory)
```sh
docker run -v $(pwd)/data/:/home/isr/data -v $(pwd)/weights/sample_weights/:/home/isr/weights -v $(pwd)/config.yml:/home/isr/config.yml -it isr -p -d -c config.yml
```

same error message.

```
Hello. This is your favorite ISR assistant.

Traceback (most recent call last):
  File "/home/isr/ISR/assistant.py", line 90, in <module>
    prediction=args['prediction'],
  File "/home/isr/ISR/assistant.py", line 17, in run
    session_type, generator, conf, dataset = setup(config_file, default, training, prediction)
  File "/home/isr/ISR/utils/utils.py", line 188, in setup
    conf['weights_paths']['generator'], conf['generators'][generator], generator
  File "/home/isr/ISR/utils/utils.py", line 61, in get_config_from_weights
    w_path = os.path.basename(w_path)
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

**Comment by amughrabi** [comment]
In ``config.yml``, you need to define the "generator" attribute first
```
default:
  generator: rrdn
```

Then, you need to download the pre-trained model in ``./weights/`` directory and map it as below:
```
weights_paths:
  discriminator:
  generator: ./weights/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5
```
See:

1. https://github.com/idealo/image-super-resolution/blob/165185cb9e0ca294f5a7719c7a4438f7204ea2b2/config.yml#L3
2. https://github.com/idealo/image-super-resolution/blob/165185cb9e0ca294f5a7719c7a4438f7204ea2b2/config.yml#L83

I do this and it works like a charm!

**Comment by jonathanmv** [comment]
It took me a while to find how to download the pre-trained model that @amughrabi mentions
I found [this comment](https://github.com/idealo/image-super-resolution/issues/129#issuecomment-649407306) where a model is downloaded from s3
```
wget https://public-asai-dl-models.s3.eu-central-1.amazonaws.com/ISR/rdn-C6-D20-G64-G064-x2/ArtefactCancelling/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5
```

**Comment by jonathanmv** [comment]
I created a [PR](https://github.com/idealo/image-super-resolution/pull/191) to address those issues
