### ISSUE TITLE
Out of Bounds Error working with my own Dataset

### ISSUE THREAD

**Issue by sephethus** [idealo/image-super-resolution#178]
I started with just 580 images. It was working fine training wise, no errors, but not improving past 24.2 after roughly 80 epochs, whatever the significance of that 24 number. I decided to add 1500 more images to the dataset. When I did I started getting this error as soon as I run it.  I tested moving the new photos back out of the directory, leaving just the dataset that did work, and yet it still gets the error. I changed nothing other than the number of steps so not sure what changed or went wrong here.

```
01:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "train.py", line 32, in <module>
    trainer = Trainer(
  File "/home/nate/image-super-resolution/ISR/train/trainer.py", line 134, in __init__
    self.valid_dh = DataHandler(
  File "/home/nate/image-super-resolution/ISR/utils/datahandler.py", line 31, in __init__
    self._make_img_list()
  File "/home/nate/image-super-resolution/ISR/utils/datahandler.py", line 47, in _make_img_list
    self.img_list[res] = self.img_list[res][samples]
IndexError: index 135 is out of bounds for axis 0 with size 132
```

Here is my training code, much like everyone else's I think. I based the step count on the number of images divided by the batch number.

```
from ISR.models import RRDN
from ISR.models import Discriminator
from ISR.train import Trainer
from ISR.models import Cut_VGG19

lr_train_patch_size = 40
layers_to_extract = [5, 9]
scale = 4
hr_train_patch_size = lr_train_patch_size * scale

rrdn  = RRDN(arch_params={'C':4, 'D':3, 'G':64, 'G0':64, 'T':10, 'x':scale}, patch_size=lr_train_patch_size)
f_ext = Cut_VGG19(patch_size=hr_train_patch_size, layers_to_extract=layers_to_extract)
discr = Discriminator(patch_size=hr_train_patch_size, kernel_size=3)

loss_weights = {
  'generator': 0.0,
  'feature_extractor': 0.0833,
  'discriminator': 0.01
}
losses = {
  'generator': 'mae',
  'feature_extractor': 'mse',
  'discriminator': 'binary_crossentropy'
} 

log_dirs = {'logs': './logs', 'weights': './weights'}

learning_rate = {'initial_value': 0.0004, 'decay_factor': 0.5, 'decay_frequency': 30}

flatness = {'min': 0.0, 'max': 0.15, 'increase': 0.01, 'increase_frequency': 5}

trainer = Trainer(
    generator=rrdn,
    discriminator=discr,
    feature_extractor=f_ext,
    lr_train_dir='data/input/training_LR/',
    hr_train_dir='data/input/training_HR/',
    lr_valid_dir='data/input/validation_LR/',
    hr_valid_dir='data/input/validation_HR/',
    loss_weights=loss_weights,
    learning_rate=learning_rate,
    flatness=flatness,
    dataname='image_dataset',
    log_dirs=log_dirs,
    n_validation=40,
)


trainer.train(
    epochs=100,
    steps_per_epoch=205,
    batch_size=10,
    monitored_metrics={'val_generator_PSNR_Y': 'max'}
)
```

**Comment by sephethus** [comment]
I keep solving my own problems these days but the answer to this riddle was that somehow, I have no idea how, some of the images in the validation folders got deleted, then they were out of sync somehow. Weird. Must've been something I mistyped in the terminal I guess.
