### ISSUE TITLE
Can't run Dockerfile.gpu. AttributeError: module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by zelkourban** [idealo/image-super-resolution#218]
Running command
```
docker run -v $(pwd)/data/:/home/isr/data -v $(pwd)/weights/:/home/isr/weights -v $(pwd)/config.yml:/home/isr/config.yml -it isr -p -d -c config.yml
```
Gets error message
```Traceback (most recent call last):
  File "/home/isr/ISR/assistant.py", line 90, in <module>
    prediction=args['prediction'],
  File "/home/isr/ISR/assistant.py", line 22, in run
    module = _get_module(generator)
  File "/home/isr/ISR/assistant.py", line 11, in _get_module
    return import_module('ISR.models.' + generator)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/isr/ISR/models/__init__.py", line 1, in <module>
    from .cut_vgg19 import Cut_VGG19
  File "/home/isr/ISR/models/cut_vgg19.py", line 1, in <module>
    from tensorflow.keras.models import Model
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/core/framework/function_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
AttributeError: module 'google.protobuf.internal.containers' has no attribute 'MutableMapping'
```

**Comment by maxcw** [comment]
I encountered the same issue
