### ISSUE TITLE
Weights

### ISSUE THREAD

**Issue by mmatties** [idealo/image-super-resolution#35]
The weights files are still not actual weights files. Could they be uploaded, please?
Thanks!

**Comment by makslevental** [comment]
yes i get this error

```
Traceback (most recent call last):
  File "/home/maksim/dev_projects/dsiac/super_resolution.py", line 10, in <module>
    rdn.model.load_weights('/home/maksim/dev_projects/dsiac/image-super-resolution/weights/rdn-C3-D10-G64-G064-x2_PSNR_epoch134.hdf5')
  File "/home/maksim/dev_projects/dsiac/venv/lib/python3.7/site-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/home/maksim/dev_projects/dsiac/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/maksim/dev_projects/dsiac/venv/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

**Comment by cfrancesco** [comment]
Refer to #21.

**Comment by makslevental** [comment]
@cfrancesco ah. sorry. thanks!
