### ISSUE TITLE
error on loading rrdn-C4-D3-G32-G032-T10-x4 weight

### ISSUE THREAD

**Issue by delphixe4** [idealo/image-super-resolution#71]
Hi,

I entered some params as insisted on the name of sample weight, but I got an error:

```
>>> rdn = RDN(arch_params={'C':4, 'D':3, 'G':32, 'G0':32, 'T':10, 'x':4})
>>> rdn.model.load_weights('E:/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5')
Traceback (most recent call last):
  File "<pyshell#178>", line 1, in <module>
    rdn.model.load_weights('E:/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5')
  File "C:\Users\xe\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\xe\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\network.py", line 1217, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Users\xe\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\saving.py", line 1171, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 154 layers into a model with 23 layers.
```

Can you help me with this problem?

**Comment by cfrancesco** [comment]
Hi, 
you are loading the wrong model. Use this instead
`
rrdn = RRDN(arch_params={'C':4, 'D':3, 'G':32, 'G0':32, 'T':10, 'x':4})
rrdn.model.load_weights('E:/rrdn-C4-D3-G32-G032-T10-x4_epoch299.hdf5')
`
